/* Game Waters service worker. Generated by build.py for one release; never hand-edit.
   The page is fetched from the network first, so a new release is seen as soon as it is
   published, with the cached copy only as an offline fallback. Icons and prints come from
   this release's cache. Other hosts (fonts, weather, rivers) are left to the browser. */
const BUILD = '98bb17209a33';
const CACHE = 'gw-' + BUILD;
const CORE = ["./", "index.html", "manifest.json", "favicon.ico", "icons/icon-16.png", "icons/icon-180.png", "icons/icon-192.png", "icons/icon-32.png", "icons/icon-48.png", "icons/icon-512.png", "prints/catch-1100.webp", "prints/catch.webp", "prints/hero-north-1100.webp", "prints/hero-north.webp", "prints/hero-south-1100.webp", "prints/hero-south.webp"];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(CORE.map(u => new Request(u, {cache: 'reload'})))));
  /* No skipWaiting here: the page activates the new release when it is safe to. */
});
self.addEventListener('message', e => { if (e.data === 'activate') self.skipWaiting(); });
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith('gw-') && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  if (url.pathname.endsWith('/version.json')) return;
  const page = req.mode === 'navigate' || url.pathname.endsWith('/') || url.pathname.endsWith('/index.html');
  if (page) {
    e.respondWith(fetch(url.pathname, {cache: 'no-store'}).then(res => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put('index.html', copy)); }
      return res;
    }).catch(() => caches.match('index.html', {ignoreSearch: true})));
    return;
  }
  e.respondWith(caches.match(req, {ignoreSearch: true}).then(hit => hit || fetch(req)));
});
